### ISSUE TITLE
.Net MAUI support

### ISSUE THREAD

**Issue by Alex-Dobrynin** [MGohil/XFPINView#10]
Please, migrate this to .Net MAUI

**Comment by MGohil** [comment]
@Alex-Dobrynin : Thanks for raising this. I am soon planning to migrate this to Maui and will update you once available.

**Comment by mbilalbenli** [comment]
Hey @MGohil, I made simple migration. Can u check out? #11

**Comment by MGohil** [comment]
@mbilalbenli : Thanks for you PR on .NET Maui Migration. As this repository is Xamarin.Forms specific control, I can not merge your Maui PR into this. 

@Alex-Dobrynin 
I am already working on .NET Maui migration and it is still under progress. I am trying to test it in various platforms and fixing issues. When all issues are fixed, I will release the nuget for it.

Maui repo can be found at: https://github.com/MGohil/PINView.Maui

Thank you for your patience!!

**Comment by MGohil** [comment]
Hi All,

.NET Maui support is now available and you can download the nuget from https://www.nuget.org/packages/PINView.Maui.

Hence, closing this.
