### ISSUE TITLE
TapGesture

### ISSUE THREAD

**Issue by angelru** [MGohil/XFPINView#7]
`[0:] Element: Xamarin.Forms.TapGestureRecognizer is already a child of XFPINView.BoxTemplate. Remove Xamarin.Forms.TapGestureRecognizer from XFPINView.BoxTemplate before adding to XFPINView.BoxTemplate.`

**Comment by MGohil** [comment]
@angelru 

I will look for this issue later (mostly in a week or two) when I get some free time. Meanwhile, would you please provide me some more details to reproduce this issue like:
- Platform
- Steps to reproduce
etc.

**Comment by apoorvadixit-ttc** [comment]
> `[0:] Element: Xamarin.Forms.TapGestureRecognizer is already a child of XFPINView.BoxTemplate. Remove Xamarin.Forms.TapGestureRecognizer from XFPINView.BoxTemplate before adding to XFPINView.BoxTemplate.`

Did you manage to fix this? I am seeing the same error in my app after upgrading to the new version of Xamarin Forms
